# 생성 및 삭제
## 데이터프레임 생성 방법

In [1]:
import pandas as pd
import numpy as np

### 1. 딕셔너리로부터 생성

In [2]:
# 1. 딕셔러리로부터 생성
# 딕셔러리 생성
product_dict = {
    'product_name': ['노트북', '마우스', '키보드', '모니터'],
    'price': [1200000, 25000, 80000, 350000],
    'stock': [10, 50, 30, 15],
    'category': ['전자제품', '주변기기', '주변기기', '전자제품']
}

In [3]:
# 데이터프레임 생성
# pd.DataFrame(data)
# pd.DataFrame(data, index)
# pd.DataFrame(data, index, columns, dtype)
df_from_dict = pd.DataFrame(product_dict)

In [4]:
print('=== 딕셔너리로부터 생성 ===')
print(df_from_dict)

=== 딕셔너리로부터 생성 ===
  product_name    price  stock category
0          노트북  1200000     10     전자제품
1          마우스    25000     50     주변기기
2          키보드    80000     30     주변기기
3          모니터   350000     15     전자제품

### 2. 리스트로부터 생성

In [5]:
# 리스트 생성
product_list = [
    ['노트북', 1200000, 10, '전자제품'],
    ['마우스', 25000, 50, '주변기기'],
    ['키보드', 80000, 30, '주변기기'],
    ['모니터', 350000, 15, '전자제품']
]

In [6]:
# 데이터프레임 생성
# pd.DataFrame(data, index, columns, dtype)
df_from_list = pd.DataFrame(
    product_list,
    columns=['product_name', 'price', 'stock', 'category'],
    index=['P001', 'P002', 'P003', 'P004']
)

In [7]:
print('=== 리스트로부터 생성(컬럼 이름과 인덱스 지정) ===')
print(df_from_list)

=== 리스트로부터 생성(컬럼 이름과 인덱스 지정) ===
     product_name    price  stock category
P001          노트북  1200000     10     전자제품
P002          마우스    25000     50     주변기기
P003          키보드    80000     30     주변기기
P004          모니터   350000     15     전자제품

### 3. NumPy 배열로부터 생성

In [8]:
# NumPy 배열 생성 - 4x3의 2차원 배열
np_array = np.random.randint(1, 100, size=(4, 3))
np_array

array([[61, 75, 59],
       [37, 12, 82],
       [16, 42, 38],
       [47, 34, 32]], dtype=int32)

In [9]:
# 데이터프레임 생성
df_from_numpy = pd.DataFrame(
    np_array,
    columns=['A', 'B', 'C'],
    index=['Row1', 'Row2', 'Row3', 'Row4']
)

In [10]:
print('=== NumPy 배열로부터 생성 ===')
print(df_from_numpy)

=== NumPy 배열로부터 생성 ===
       A   B   C
Row1  61  75  59
Row2  37  12  82
Row3  16  42  38
Row4  47  34  32

### 4. 빈 데이터프레임 생성 후 데이터 추가

In [11]:
# 빈 데이터프레임 생성
empty_df = pd.DataFrame(
    columns=['name', 'age', 'city']
)

In [12]:
# 딕셔너리로 데이터프레임 생성
new_data = pd.DataFrame({
    'name': ['김철수', '이영희'],
    'age': [25, 30],
    'city': ['서울', '부산']
})
new_data

  name  age city
0  김철수   25   서울
1  이영희   30   부산

In [13]:
# pd.concat()
# concatenate: 연결하다
df_combined = pd.concat(
    [empty_df, new_data],
    ignore_index=True
)

In [14]:
print('=== 빈 데이터프레임에 데이터 추가 ===')
print(df_combined)

=== 빈 데이터프레임에 데이터 추가 ===
  name age city
0  김철수  25   서울
1  이영희  30   부산

## 외부 파일에서 데이터 불러오기

In [15]:
# 1. csv 퍄일 불러오기
file_name = 'https://raw.githubusercontent.com/zzhining/python_data_basic2/refs/heads/main/3%EC%9E%A5/sample_products.csv'

# pd.read_csv(파일명, encoding='utf-8')
df_csv = pd.read_csv(file_name, encoding='utf-8')

In [16]:
print('=== csv 파일 불러오기 ===')
print(df_csv)

=== csv 파일 불러오기 ===
  product_id product_name    price category
0       P001          노트북  1200000     전자제품
1       P002          마우스    25000     주변기기
2       P003          키보드    80000     주변기기
3       P004          모니터   350000     전자제품
4       P005          스피커   120000     주변기기

In [17]:
# 2. cvs 파일 불러오기 시 조건 지정
# 특정 컬럼과 상위 3행만 가져온다.
df_filtered = pd.read_csv(
    file_name,
    encoding='utf-8',
    usecols=['product_name', 'price', 'category'],
    nrows=3
)

print('=== 조건을 지정하여 불러오기 ===')
print(df_filtered)

=== 조건을 지정하여 불러오기 ===
  product_name    price category
0          노트북  1200000     전자제품
1          마우스    25000     주변기기
2          키보드    80000     주변기기

## 데이터 프레임 복사

In [18]:
# 원본 데이터프레임 생성
original_df = pd.DataFrame({
    'name': ['김모씨', '이모씨', '박모씨'],
    'age': [25, 30, 35],
    'salary': [3000, 4000, 5000]
})
print('=== 원본 데이터프레임 ===')
print(original_df)

=== 원본 데이터프레임 ===
  name  age  salary
0  김모씨   25    3000
1  이모씨   30    4000
2  박모씨   35    5000

In [19]:
# 깊은 복사 vs 참조 복사
# 깊은 복사: df.copy()
deep_copy_df = original_df.copy()

# 참조 복사
reference_df = original_df

In [20]:
deep_copy_df

  name  age  salary
0  김모씨   25    3000
1  이모씨   30    4000
2  박모씨   35    5000

In [21]:
reference_df

  name  age  salary
0  김모씨   25    3000
1  이모씨   30    4000
2  박모씨   35    5000

In [22]:
# 특정 아이템 선택
# deep_copy_df.loc[행, 열]
deep_copy_df.loc[0, 'salary'] = 3500
reference_df.loc[1, 'age'] = 31

In [23]:
print('=== 깊은 복사 후 수정 ===')
print('원본:')
print(original_df)
print('복사본:')
print(deep_copy_df)

=== 깊은 복사 후 수정 ===
원본:
  name  age  salary
0  김모씨   25    3000
1  이모씨   31    4000
2  박모씨   35    5000
복사본:
  name  age  salary
0  김모씨   25    3500
1  이모씨   30    4000
2  박모씨   35    5000

In [24]:
print('=== 참조 복사 후 참조 데이터 변경 ===')
print('원본 (참조 복사로 인해 변경됨):')
print(original_df)
print('참조 복사본:')
print(reference_df)

=== 참조 복사 후 참조 데이터 변경 ===
원본 (참조 복사로 인해 변경됨):
  name  age  salary
0  김모씨   25    3000
1  이모씨   31    4000
2  박모씨   35    5000
참조 복사본:
  name  age  salary
0  김모씨   25    3000
1  이모씨   31    4000
2  박모씨   35    5000

## 행과 열 삭제

In [25]:
# 데이터 생성
test_data = pd.DataFrame({
    'id': [1, 2, 3, 4, 5, 6],
    'name': ['김철수', '이영희', '박민수', '김철수', '정수진', '이영희'],
    'age': [25, 30, None, 25, 28, 30],
    'city': ['서울', '부산', '대구', '서울', None, '부산'],
    'salary': [3000, 4000, 5000, 3000, 3500, 4000],
    'temp_col': ['임시', '임시', '임시', '임시', '임시', '임시']
})

print(' === 원본 데이터 ===')
print(test_data)

 === 원본 데이터 ===
   id name   age city  salary temp_col
0   1  김철수  25.0   서울    3000       임시
1   2  이영희  30.0   부산    4000       임시
2   3  박민수   NaN   대구    5000       임시
3   4  김철수  25.0   서울    3000       임시
4   5  정수진  28.0  NaN    3500       임시
5   6  이영희  30.0   부산    4000       임시

In [ ]:
# 2. 하나의 열 삭제 (컬럼명 기준)
# df.drop('열이름', axis)
# axis: 삭제 축(0=행, 1=열)
df_drop_col = test_data.drop('temp_col', axis=1)
print('\n=== 열 삭제 후 ===')
print(df_drop_col)

=== 열 삭제 후 ===
   id name   age city  salary
0   1  김철수  25.0   서울    3000
1   2  이영희  30.0   부산    4000
2   3  박민수   NaN   대구    5000
3   4  김철수  25.0   서울    3000
4   5  정수진  28.0  NaN    3500
5   6  이영희  30.0   부산    4000

In [28]:
# test_data
# 2. 여러 열 삭제
df_drop_cols = test_data.drop(['temp_col', 'id'], axis=1)
print('\n=== 열 삭제 후 ===')
print(df_drop_cols)

=== 열 삭제 후 ===
  name   age city  salary
0  김철수  25.0   서울    3000
1  이영희  30.0   부산    4000
2  박민수   NaN   대구    5000
3  김철수  25.0   서울    3000
4  정수진  28.0  NaN    3500
5  이영희  30.0   부산    4000

In [29]:
# 3. 특정 행 삭제 (인덱스 기준)
df_drop_row = test_data.drop([0, 5], axis=0)
print('=== 특정 행 삭제 후 ===')
print(df_drop_row)

=== 특정 행 삭제 후 ===
   id name   age city  salary temp_col
1   2  이영희  30.0   부산    4000       임시
2   3  박민수   NaN   대구    5000       임시
3   4  김철수  25.0   서울    3000       임시
4   5  정수진  28.0  NaN    3500       임시

In [ ]:
# 4. 중복 행 삭제
# df_no_duplicates(subset=['컬럼명', ...], keep='first')
#  keep: 'first'(기본값), 'last', False(모두 삭제)
df_no_duplicates = test_data.drop_duplicates(subset=['name', 'age'], keep='first')
print('=== 중복 행 삭제 후 (name, age 기준) ===')
print(df_no_duplicates)

=== 중복 행 삭제 후 (name, age 기준) ===
   id name   age city  salary temp_col
0   1  김철수  25.0   서울    3000       임시
1   2  이영희  30.0   부산    4000       임시
2   3  박민수   NaN   대구    5000       임시
4   5  정수진  28.0  NaN    3500       임시

In [ ]:
# 5. 결측치(NaN)가 있는 행 삭제
df_no_na = test_data.dropna()
print('=== 결축치 행 삭제 후 ===')
print(df_no_na)

=== 결축치 행 삭제 후 ===
   id name   age city  salary temp_col
0   1  김철수  25.0   서울    3000       임시
1   2  이영희  30.0   부산    4000       임시
3   4  김철수  25.0   서울    3000       임시
5   6  이영희  30.0   부산    4000       임시

In [32]:
# 6. 특정 컬럼의 결측치만 삭제
df_no_na_age = test_data.dropna(subset=['age'])
print('=== age 컬럼 결측치 행 삭제 ===')
print(df_no_na_age)

=== age 컬럼 결측치 행 삭제 ===
   id name   age city  salary temp_col
0   1  김철수  25.0   서울    3000       임시
1   2  이영희  30.0   부산    4000       임시
3   4  김철수  25.0   서울    3000       임시
4   5  정수진  28.0  NaN    3500       임시
5   6  이영희  30.0   부산    4000       임시

## 데이터프레임 저장

In [34]:
# 데이터프레임 생성
save_data = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P003', 'P004'],
    'product_name': ['노트북', '마우스', '키보드', '모니터'],
    'price': [1200000, 25000, 80000, 350000],
    'category': ['전자제품', '주변기기', '주변기기', '전자제품'],
    'reg_date': pd.date_range('2024-01-01', periods=4, freq='D')
})

print('=== 저장할 데이터 ===')
print(save_data)

=== 저장할 데이터 ===
  product_id product_name    price category   reg_date
0       P001          노트북  1200000     전자제품 2024-01-01
1       P002          마우스    25000     주변기기 2024-01-02
2       P003          키보드    80000     주변기기 2024-01-03
3       P004          모니터   350000     전자제품 2024-01-04

In [35]:
# csv(comma seperated values) 파일로 저장
save_data.to_csv('products_output_csv', index=False)
print('=== csv 파일 저장 완료 ===')

=== csv 파일 저장 완료 ===