# 기본 그래프 유형
## 선 그래프(line plot)

In [50]:
from datetime import datetime, timedelta

import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots

In [2]:
num = np.random.randn(30)
num

array([ 0.63420306, -1.28695947,  0.6497145 ,  0.71950492,  0.8777195 ,
        0.56329992,  0.11113963, -0.43426151, -0.42584339, -1.13199887,
        0.88896813,  0.33809519, -0.62810958,  0.45762126,  0.1513015 ,
       -0.17077849, -0.16556573, -1.77851463, -0.19506694,  0.73487686,
        0.85904229, -1.44594858, -1.36725758, -1.38859251,  0.53018055,
        0.70315656,  0.20320262,  1.07742498, -0.29714077,  0.26476668])

In [3]:
# 시계열 데이터 생성
# 2024-01-01 부터 D(Daily) 하루씩 30일간
dates = pd.date_range('2026-06-01', periods=30, freq='D')
# np.random.randn(30): 평균 0, 표준편차 1에 따른 난수 30개
values = np.cumsum(np.random.randn(30)) + 100

time_series = pd.DataFrame({
    '날짜': dates,
    '주가': values
})
time_series

           날짜          주가
0  2026-06-01   99.180510
1  2026-06-02   99.633076
2  2026-06-03   98.307195
3  2026-06-04   99.613235
4  2026-06-05   99.965040
5  2026-06-06  100.551413
6  2026-06-07   99.367350
7  2026-06-08   98.870515
8  2026-06-09   99.300338
9  2026-06-10  100.391191
10 2026-06-11  101.745111
11 2026-06-12  102.252955
12 2026-06-13  103.735359
13 2026-06-14  102.052162
14 2026-06-15  102.185868
15 2026-06-16  101.273424
16 2026-06-17  102.660004
17 2026-06-18  103.508007
18 2026-06-19  104.149346
19 2026-06-20  104.959487
20 2026-06-21  104.073307
21 2026-06-22  103.706920
22 2026-06-23  103.271166
23 2026-06-24  104.480968
24 2026-06-25  104.299533
25 2026-06-26  104.433112
26 2026-06-27  104.172817
27 2026-06-28  105.157226
28 2026-06-29  106.006311
29 2026-06-30  106.366428

In [6]:
# 1. 단일 선 그래프
fig = px.line(
    time_series, 
    x='날짜', 
    y='주가',
    title='일일 주가 변동',
    markers=True
)
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '날짜=%{x}<br>주가=%{y}<extra></extra>',
              'legendgroup': '',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines+markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array(['2026-06-01T00:00:00.000000', '2026-06-02T00:00:00.000000',
                          '2026-06-03T00:00:00.000000', '2026-06-04T00:00:00.000000',
                          '2026-06-05T00:00:00.000000', '2026-06-06T00:00:00.000000',
                          '2026-06-07T00:00:00.000000', '2026-06-08T00:00:00.000000',
                          '2026-06-09T00:00:00.000000', '2026-06-10T00:00:00.000000',
                          '2026-06-11T00:00:00.000000', '2026-06-12T00:00:00.000000',
                          '2026-06-13T00:00:00.000000', '2026-06-14T00:00:00.000000',
                          '2026-06-15T00:00:00.000000', '2026-06-16T00:00:00.000000',
                          '2026-06-17T00:00:00.000000', '2026-06-18T00:00:00.000000',
                          '2026-06-19T00:00:00.000000', '2026-06-20T00:00:00.000000',
                          '2026-06-21T00:00:00.000000', '2026-06-22T00:00:00.000000',
                          '2026-06-23T00:00:00.000000', '2026-06-24T00:00:00.000000',
                          '2026-06-25T00:00:00.000000', '2026-06-26T00:00:00.000000',
                          '2026-06-27T00:00:00.000000', '2026-06-28T00:00:00.000000',
                          '2026-06-29T00:00:00.000000', '2026-06-30T00:00:00.000000'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'y': {'bdata': ('tzTbeo3LWEA2fn5ShOhYQB6Y8Rapk1' ... 'bb/g9KWkC0PkFoZ4BaQCChwY9zl1pA'),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '일일 주가 변동'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '날짜'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '주가'}}}
})

In [7]:
num = np.cumsum(np.random.randn(1))[0]
print(num)
# 참고: 숫자 범위 제한 없다.

-2.1034165829903064

In [8]:
# 2. 다중 선 그래프
# 데이터 생성
companies = ['삼성전자', 'LG전자', 'SK하이닉스']
stock_data = []

for company in companies:
    for i, date in enumerate(dates):
        price = 100 + np.cumsum(np.random.randn(1))[0] * (i + 1) / 10
        stock_data.append({
            '날짜': date,
            '회사': company,
            '주가': price
        })

# 데이터 분석
df_stocks = pd.DataFrame(stock_data)
df_stocks

           날짜      회사          주가
0  2026-06-01    삼성전자  100.062504
1  2026-06-02    삼성전자  100.216416
2  2026-06-03    삼성전자   99.792032
3  2026-06-04    삼성전자   99.667839
4  2026-06-05    삼성전자   99.989105
..        ...     ...         ...
85 2026-06-26  SK하이닉스  102.654840
86 2026-06-27  SK하이닉스   98.393392
87 2026-06-28  SK하이닉스  100.577333
88 2026-06-29  SK하이닉스  101.778042
89 2026-06-30  SK하이닉스   94.118786

[90 rows x 3 columns]

# 선 스타일
- solid
- dot, 
- dash
- longdash
- dashdot
- longdashdot

In [9]:
# 데이터 시각화
fig = px.line(
    df_stocks,
    x='날짜', # x축 컬럼명
    y='주가', # y축 컬럼명
    color='회사', # 그룹별 색상
    title='회사멸 주가 비교', # 차트 제목
    line_dash='회사', # 선 스타일

    category_orders={
        '회사': ['삼성전자', 'LG전자', 'SK하이닉스']
    },

    # color_discrete_sequence={'lightblue', 'orange', 'lightgreen'}

    color_discrete_map={
        '삼성전자': 'orange',
        'LG전자': 'yellow',
        'SK하이닉스': 'lime'
    },

    line_dash_map={
        '삼성전자': 'solid',
        'LG전자': 'dot',
        'SK하이닉스': 'dash'
    }
)
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '회사=삼성전자<br>날짜=%{x}<br>주가=%{y}<extra></extra>',
              'legendgroup': '삼성전자',
              'line': {'color': 'orange', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': '삼성전자',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2026-06-01T00:00:00.000000', '2026-06-02T00:00:00.000000',
                          '2026-06-03T00:00:00.000000', '2026-06-04T00:00:00.000000',
                          '2026-06-05T00:00:00.000000', '2026-06-06T00:00:00.000000',
                          '2026-06-07T00:00:00.000000', '2026-06-08T00:00:00.000000',
                          '2026-06-09T00:00:00.000000', '2026-06-10T00:00:00.000000',
                          '2026-06-11T00:00:00.000000', '2026-06-12T00:00:00.000000',
                          '2026-06-13T00:00:00.000000', '2026-06-14T00:00:00.000000',
                          '2026-06-15T00:00:00.000000', '2026-06-16T00:00:00.000000',
                          '2026-06-17T00:00:00.000000', '2026-06-18T00:00:00.000000',
                          '2026-06-19T00:00:00.000000', '2026-06-20T00:00:00.000000',
                          '2026-06-21T00:00:00.000000', '2026-06-22T00:00:00.000000',
                          '2026-06-23T00:00:00.000000', '2026-06-24T00:00:00.000000',
                          '2026-06-25T00:00:00.000000', '2026-06-26T00:00:00.000000',
                          '2026-06-27T00:00:00.000000', '2026-06-28T00:00:00.000000',
                          '2026-06-29T00:00:00.000000', '2026-06-30T00:00:00.000000'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'y': {'bdata': ('yU7bDgAEWUCR5zTB2Q1ZQBIiH6Ww8l' ... 'KHF4M4WUAUdpnGiehYQEWYjfwYmlhA'),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'hovertemplate': '회사=LG전자<br>날짜=%{x}<br>주가=%{y}<extra></extra>',
              'legendgroup': 'LG전자',
              'line': {'color': 'yellow', 'dash': 'dot'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'LG전자',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2026-06-01T00:00:00.000000', '2026-06-02T00:00:00.000000',
                          '2026-06-03T00:00:00.000000', '2026-06-04T00:00:00.000000',
                          '2026-06-05T00:00:00.000000', '2026-06-06T00:00:00.000000',
                          '2026-06-07T00:00:00.000000', '2026-06-08T00:00:00.000000',
                          '2026-06-09T00:00:00.000000', '2026-06-10T00:00:00.000000',
                          '2026-06-11T00:00:00.000000', '2026-06-12T00:00:00.000000',
                          '2026-06-13T00:00:00.000000', '2026-06-14T00:00:00.000000',
                          '2026-06-15T00:00:00.000000', '2026-06-16T00:00:00.000000',
                          '2026-06-17T00:00:00.000000', '2026-06-18T00:00:00.000000',
                          '2026-06-19T00:00:00.000000', '2026-06-20T00:00:00.000000',
                          '2026-06-21T00:00:00.000000', '2026-06-22T00:00:00.000000',
                          '2026-06-23T00:00:00.000000', '2026-06-24T00:00:00.000000',
                          '2026-06-25T00:00:00.000000', '2026-06-26T00:00:00.000000',
                          '2026-06-27T00:00:00.000000', '2026-06-28T00:00:00.000000',
                          '2026-06-29T00:00:00.000000', '2026-06-30T00:00:00.000000'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'y': {'bdata': ('2/oLoIQOWUDanUVy4vNYQMfq09xeGl' ... 'INF6BsWUDig5FkNL5YQPGb6c+B71hA'),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'hovertemplate': '회사=SK하이닉스<br>날짜=%{x}<br>주가=%{y}<extra></extra>',
              'legendgroup': 'SK하이닉스',
              'line': {'color': 'lime', 'dash': 'dash'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'SK하이닉스',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2026-06-01T00:00:00.000000', '2026-06-02T00:00:00.000000',
                          '2026-06-03T00:00:00.000000', '2026-06-04T00:00:00.000000',
                          '2026-06-05T00:00:00.000000', '2026-06-06T00:00:00.000000',
                          '2026-06-07T00:00:00.000000', '2026-06-08T00:00:00.000000',
                          '2026-06-09T00:00:00.000000', '2026-06-10T00:00:00.000000',
                          '2026-06-11T00:00:00.000000', '2026-06-12T00:00:00.000000',
                          '2026-06-13T00:00:00.000000', '2026-06-14T00:00:00.000000',
                          '2026-06-15T00:00:00.000000', '2026-06-16T00:00:00.000000',
                          '2026-06-17T00:00:00.000000', '2026-06-18T00:00:00.000000',
                          '2026-06-19T00:00:00.000000', '2026-06-20T00:00:00.000000',
                          '2026-06-21T00:00:00.000000', '2026-06-22T00:00:00.000000',
                          '2026-06-23T00:00:00.000000', '2026-06-24T00:00:00.000000',
                          '2026-06-25T00:00:00.000000', '2026-06-26T00:00:00.000000',
                          '2026-06-27T00:00:00.000000', '2026-06-28T00:00:00.000000',
                          '2026-06-29T00:00:00.000000', '2026-06-30T00:00:00.000000'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'y': {'bdata': ('8Edd1i8CWUC6tXdJTvFYQMJL466H/V' ... 'UsCPMkWUBEibRwy3FZQBFW3y6ah1dA'),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': '회사'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '회사멸 주가 비교'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '날짜'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '주가'}}}
})

## 삼점도(scatter plot)

In [10]:
# 1. 기본 산점도
# 키와 몸무게 데이터
height_weight = {
    '키': [160, 165, 170, 175, 180, 162, 168, 172, 178, 185],
    '몸무게': [55, 60, 65, 70, 75, 58, 63, 68, 73, 80],
    '성별': ['여성', '여성', '여성', '남성', '남성', '여성', '여성', '남성', '남성', '남성']
}

df_body = pd.DataFrame(height_weight)
df_body

     키  몸무게  성별
0  160   55  여성
1  165   60  여성
2  170   65  여성
3  175   70  남성
4  180   75  남성
5  162   58  여성
6  168   63  여성
7  172   68  남성
8  178   73  남성
9  185   80  남성

In [11]:
fig = px.scatter(df_body, x='키', y='몸무게', title='키와 몸무게의 관계')
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '키=%{x}<br>몸무게=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': {'bdata': 'oAClAKoArwC0AKIAqACsALIAuQA=', 'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': 'NzxBRks6P0RJUA==', 'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '키와 몸무게의 관계'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '키'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '몸무게'}}}
})

In [12]:
# 2. 그룹별 산점도
# 성별로 구분한 산점도
fig = px.scatter(
    df_body, # 데이터프레임
    x='키', # x축 컬럼 -> x축 값 및 이름
    y='몸무게', # y축 컬럼 -> y축 값 및 이름
    color='성별', # 그룹별 색상 -> 범례
    title='성별에 따른 키와 몸무게 관계', # 그래프 제목
    size_max=15 # 마커의 최대 크기
)

# 축 제목 변경
fig.update_layout(
    xaxis_title='키 (cm)',
    yaxis_title='몸무게 (kg)'
)

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '성별=여성<br>키=%{x}<br>몸무게=%{y}<extra></extra>',
              'legendgroup': '여성',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '여성',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': 'oAClAKoAogCoAA==', 'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': 'NzxBOj8=', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': '성별=남성<br>키=%{x}<br>몸무게=%{y}<extra></extra>',
              'legendgroup': '남성',
              'marker': {'color': '#EF553B', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '남성',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': 'rwC0AKwAsgC5AA==', 'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': 'RktESVA=', 'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': '성별'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '성별에 따른 키와 몸무게 관계'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '키 (cm)'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '몸무게 (kg)'}}}
})

In [13]:
# 3. 버블 차트
# 크키까지 고려한 버블 차트
# 데이터 생성(직접, 크롤링)
countries = {
    '국가': ['한국', '일본', '중국', '미국', '독일'],
    'GDP': [1800, 4200, 14000, 21000, 3800],
    '인구': [51, 126, 1400, 330, 83],
    '대륙': ['아시아', '아시아', '아시아', '북미', '유럽']
}

# 데이터 분석(전처리 -> 데이터 다듬기, 통계)
df_countries = pd.DataFrame(countries)
df_countries

   국가    GDP    인구   대륙
0  한국   1800    51  아시아
1  일본   4200   126  아시아
2  중국  14000  1400  아시아
3  미국  21000   330   북미
4  독일   3800    83   유럽

In [14]:
# 데이터 시각화
fig = px.scatter(
    df_countries, 
    x='GDP', 
    y='인구',
    size='GDP',
    color='대륙',
    hover_name='국가',
    title='국가별 DGP와 인구 관계',
    size_max=60,
    labels={ # 축 제목
        'GDP': 'GDP (억 달러)',
        '인구': '인구 (백만명)'
    }
)

# fig.update_layout(
#     xaxis_title='GDP (억 달러)',
#     yaxis_title='인구 (백만명)'
# )

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': ('<b>%{hovertext}</b><br><br>대륙=' ... 'r>인구 (백만명)=%{y}<extra></extra>'),
              'hovertext': array(['한국', '일본', '중국'], dtype=object),
              'legendgroup': '아시아',
              'marker': {'color': '#636efa',
                         'size': {'bdata': 'CAdoELA2', 'dtype': 'i2'},
                         'sizemode': 'area',
                         'sizeref': 5.833333333333333,
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': '아시아',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': 'CAdoELA2', 'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': 'MwB+AHgF', 'dtype': 'i2'},
              'yaxis': 'y'},
             {'hovertemplate': ('<b>%{hovertext}</b><br><br>대륙=' ... 'r>인구 (백만명)=%{y}<extra></extra>'),
              'hovertext': array(['미국'], dtype=object),
              'legendgroup': '북미',
              'marker': {'color': '#EF553B',
                         'size': {'bdata': 'CFI=', 'dtype': 'i2'},
                         'sizemode': 'area',
                         'sizeref': 5.833333333333333,
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': '북미',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': 'CFI=', 'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': 'SgE=', 'dtype': 'i2'},
              'yaxis': 'y'},
             {'hovertemplate': ('<b>%{hovertext}</b><br><br>대륙=' ... 'r>인구 (백만명)=%{y}<extra></extra>'),
              'hovertext': array(['독일'], dtype=object),
              'legendgroup': '유럽',
              'marker': {'color': '#00cc96',
                         'size': {'bdata': '2A4=', 'dtype': 'i2'},
                         'sizemode': 'area',
                         'sizeref': 5.833333333333333,
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': '유럽',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': '2A4=', 'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': 'Uw==', 'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'legend': {'itemsizing': 'constant', 'title': {'text': '대륙'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '국가별 DGP와 인구 관계'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'GDP (억 달러)'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '인구 (백만명)'}}}
})

# 막대 그래프(bar chart)

In [15]:
# 1. 세로 막대 그래프
# 과목별 데이터 생성
# 과목별 점수 데이터
subjects = {
    '과목': ['수학', '영어', '국어', '과학', '사회'],
    '점수': [85, 92, 78, 88, 82]
}

subjects

{'과목': ['수학', '영어', '국어', '과학', '사회'], '점수': [85, 92, 78, 88, 82]}

In [16]:
# 데이터 분석
df_scores = pd.DataFrame(subjects)
df_scores

   과목  점수
0  수학  85
1  영어  92
2  국어  78
3  과학  88
4  사회  82

In [17]:
print(px.colors.named_colorscales())

['aggrnyl', 'agsunset', 'blackbody', 'bluered', 'blues', 'blugrn', 'bluyl', 'brwnyl', 'bugn', 'bupu', 'burg', 'burgyl', 'cividis', 'darkmint', 'electric', 'emrld', 'gnbu', 'greens', 'greys', 'hot', 'inferno', 'jet', 'magenta', 'magma', 'mint', 'orrd', 'oranges', 'oryel', 'peach', 'pinkyl', 'plasma', 'plotly3', 'pubu', 'pubugn', 'purd', 'purp', 'purples', 'purpor', 'rainbow', 'rdbu', 'rdpu', 'redor', 'reds', 'sunset', 'sunsetdark', 'teal', 'tealgrn', 'turbo', 'viridis', 'ylgn', 'ylgnbu', 'ylorbr', 'ylorrd', 'algae', 'amp', 'deep', 'dense', 'gray', 'haline', 'ice', 'matter', 'solar', 'speed', 'tempo', 'thermal', 'turbid', 'armyrose', 'brbg', 'earth', 'fall', 'geyser', 'prgn', 'piyg', 'picnic', 'portland', 'puor', 'rdgy', 'rdylbu', 'rdylgn', 'spectral', 'tealrose', 'temps', 'tropic', 'balance', 'curl', 'delta', 'oxy', 'edge', 'hsv', 'icefire', 'phase', 'twilight', 'mrybm', 'mygbm']

In [18]:
# 데이터 시각화
fig = px.bar(
    df_scores,
    x='과목',
    y='점수',
    title='과목별 점수',
    color='점수',
    color_continuous_scale='Blues'
)
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '과목=%{x}<br>점수=%{marker.color}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'VVxOWFI=', 'dtype': 'i1'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학', '사회'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'VVxOWFI=', 'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'autocolorscale': False,
                             'colorbar': {'title': {'text': '점수'}},
                             'colorscale': [[0.0, 'rgb(247,251,255)'], [0.125,
                                            'rgb(222,235,247)'], [0.25,
                                            'rgb(198,219,239)'], [0.375,
                                            'rgb(158,202,225)'], [0.5,
                                            'rgb(107,174,214)'], [0.625,
                                            'rgb(66,146,198)'], [0.75,
                                            'rgb(33,113,181)'], [0.875,
                                            'rgb(8,81,156)'], [1.0,
                                            'rgb(8,48,107)']]},
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '과목별 점수'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '과목'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '점수'}}}
})

In [19]:
# 2. 가로 막대 그래프
fig = px.bar(
    df_scores,
    x='점수', 
    y='과목',
    title='과목별 점수 (가로형)',
    orientation='h', # 기본값: v(vertical, 수직) / horizontal(수평)
    color='점수',
    color_continuous_scale='Viridis'
)
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '점수=%{marker.color}<br>과목=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': {'bdata': 'VVxOWFI=', 'dtype': 'i1'},
                         'coloraxis': 'coloraxis',
                         'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'h',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'VVxOWFI=', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': array(['수학', '영어', '국어', '과학', '사회'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'coloraxis': {'autocolorscale': False,
                             'colorbar': {'title': {'text': '점수'}},
                             'colorscale': [[0.0, '#440154'], [0.1111111111111111,
                                            '#482878'], [0.2222222222222222,
                                            '#3e4989'], [0.3333333333333333,
                                            '#31688e'], [0.4444444444444444,
                                            '#26828e'], [0.5555555555555556,
                                            '#1f9e89'], [0.6666666666666666,
                                            '#35b779'], [0.7777777777777778,
                                            '#6ece58'], [0.8888888888888888,
                                            '#b5de2b'], [1.0, '#fde725']]},
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '과목별 점수 (가로형)'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '점수'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '과목'}}}
})

In [20]:
# 3. 그룹 막대 그래프
# 학급별 과목 점수 비교
# 데이터 생성
class_scores = {
    '과목': ['수학', '영어', '국어', '과학'] * 3,
    '점수': [85, 92, 78, 88, 82, 88, 75, 90, 80, 85, 82, 86],
    '학급': ['1반'] * 4 + ['2반'] * 4 + ['3반'] * 4
}

In [21]:
# 데이터 분석
df_class = pd.DataFrame(class_scores)
df_class

    과목  점수  학급
0   수학  85  1반
1   영어  92  1반
2   국어  78  1반
3   과학  88  1반
4   수학  82  2반
5   영어  88  2반
6   국어  75  2반
7   과학  90  2반
8   수학  80  3반
9   영어  85  3반
10  국어  82  3반
11  과학  86  3반

In [22]:
# 데이터 시각화
fig = px.bar(
    df_class, 
    x='과목', 
    y='점수',
    color='학급',
    title='학급별 과목 점수 비교',
    barmode='group' # 'stack'으로 변경하면 누적 막대
)

fig.update_layout(
    xaxis_title='과목',
    yaxis_title='점수'
)

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'hovertemplate': '학급=1반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '1반',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '1반',
              'offsetgroup': '1반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'VVxOWA==', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': '학급=2반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '2반',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '2반',
              'offsetgroup': '2반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'UlhLWg==', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': '학급=3반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '3반',
              'marker': {'color': '#00cc96', 'pattern': {'shape': ''}},
              'name': '3반',
              'offsetgroup': '3반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'UFVSVg==', 'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'group',
               'legend': {'title': {'text': '학급'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '학급별 과목 점수 비교'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '과목'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '점수'}}}
})

In [23]:
# 데이터 시각화
# 누적 세로 막대 그래프
fig = px.bar(
    df_class, 
    x='과목', 
    y='점수',
    color='학급',
    title='학급별 과목 점수 비교',
    barmode='stack' # 'stack'으로 변경하면 누적 막대
)

fig.update_layout(
    xaxis_title='과목',
    yaxis_title='점수'
)

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '학급=1반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '1반',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '1반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'VVxOWA==', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': '학급=2반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '2반',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '2반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'UlhLWg==', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': '학급=3반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '3반',
              'marker': {'color': '#00cc96', 'pattern': {'shape': ''}},
              'name': '3반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'UFVSVg==', 'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'stack',
               'legend': {'title': {'text': '학급'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '학급별 과목 점수 비교'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '과목'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '점수'}}}
})

In [24]:
# 데이터 시각화
# 누적 세로 막대 그래프
fig = px.bar(
    df_class, 
    x='과목', 
    y='점수',
    color='학급',
    title='학급별 과목 점수 비교',
    barmode='overlay' # 'stack'으로 변경하면 누적 막대
)

fig.update_layout(
    xaxis_title='과목',
    yaxis_title='점수'
)

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '학급=1반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '1반',
              'marker': {'color': '#636efa', 'opacity': 0.5, 'pattern': {'shape': ''}},
              'name': '1반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'VVxOWA==', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': '학급=2반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '2반',
              'marker': {'color': '#EF553B', 'opacity': 0.5, 'pattern': {'shape': ''}},
              'name': '2반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'UlhLWg==', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': '학급=3반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '3반',
              'marker': {'color': '#00cc96', 'opacity': 0.5, 'pattern': {'shape': ''}},
              'name': '3반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'UFVSVg==', 'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'overlay',
               'legend': {'title': {'text': '학급'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '학급별 과목 점수 비교'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '과목'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '점수'}}}
})

In [25]:
# 데이터 시각화
# 누적 세로 막대 그래프
fig = px.bar(
    df_class, 
    x='과목', 
    y='점수',
    color='학급',
    title='학급별 과목 점수 비교',
    # barmode='relative' # 'stack'으로 변경하면 누적 막대
)

fig.update_layout(
    xaxis_title='과목',
    yaxis_title='점수'
)

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '학급=1반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '1반',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '1반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'VVxOWA==', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': '학급=2반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '2반',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '2반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'UlhLWg==', 'dtype': 'i1'},
              'yaxis': 'y'},
             {'hovertemplate': '학급=3반<br>과목=%{x}<br>점수=%{y}<extra></extra>',
              'legendgroup': '3반',
              'marker': {'color': '#00cc96', 'pattern': {'shape': ''}},
              'name': '3반',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['수학', '영어', '국어', '과학'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'UFVSVg==', 'dtype': 'i1'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': '학급'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '학급별 과목 점수 비교'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '과목'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': '점수'}}}
})

## 히스토그램(histogram)

In [26]:
# 1. 기본 히스토그램
# 시험 점수 분포 데이터
# 데이터 생성
# NumPy의 난수만 고정
np.random.seed(42)
# 평균 75, 표준편차 15
# np.random.normal(평균, 표준편차, 개수)
# 평균 75, 표준편차 15인 정규분포(normal distribution)에서 랜덤 숫자 1000개를 생성
scores = np.random.normal(75, 15, 1000)
# 0-100 사이로 제한
# np.clip(배열, 최소값, 최대값)
scores = np.clip(scores, 0, 100)
scores

array([ 82.4507123 ,  72.92603548,  84.71532807,  97.84544785,
        71.48769938,  71.48794565,  98.68819223,  86.51152094,
        67.95788421,  83.13840065,  68.04873461,  68.0140537 ,
        78.62943407,  46.30079633,  49.12623251,  66.56568706,
        59.80753319,  79.71370999,  61.37963887,  53.81544448,
        96.98473153,  71.61335549,  76.01292307,  53.62877721,
        66.83425913,  76.66383885,  57.73509634,  80.63547028,
        65.99041965,  70.62459375,  65.97440082, 100.        ,
        74.79754163,  59.13433607,  87.33817368,  56.68734525,
        78.13295393,  45.60494814,  55.07720927,  77.95291854,
        86.0769987 ,  77.57052422,  73.26527576,  70.48344457,
        52.82217014,  64.20233687,  68.09041844,  90.85683339,
        80.15427434,  48.55439767,  79.86125954,  69.22376579,
        64.84617   ,  84.17514433,  90.46499284,  88.96920179,
        62.41173715,  70.36181436,  79.96895147,  89.63317691,
        67.81238643,  72.21511535,  58.40497539,  57.05690064,
        87.18788734,  95.34360043,  73.91984818,  90.05299347,
        80.42454038,  65.32320368,  80.42093408,  98.0705485 ,
        74.46260941,  98.46965484,  35.70382344,  87.32853757,
        76.30570602,  70.51488974,  76.37641165,  45.18646628,
        71.70492168,  80.35668857,  97.16841067,  67.22594673,
        62.87259596,  67.47364435,  88.73103177,  79.93126664,
        67.05359694,  82.6990115 ,  76.45616324,  89.52967486,
        64.46920359,  70.0850678 ,  69.1183777 ,  53.04727578,
        79.44180416,  78.91582908,  75.07670185,  71.481193  ,
        53.76943887,  68.69032016,  69.85928225,  62.96584096,
        72.58071433,  81.06076285, 100.        ,  77.61866719,
        78.86325586,  73.88331126,  46.21843177,  74.60229187,
        75.90345315, 100.        ,  72.11458553,  79.52321014,
        74.47932345,  57.46982944,  92.14234222,  86.27899549,
        86.86547921,  61.35918818,  96.04191466,  53.97223406,
        83.80285641, 100.        ,  60.14195512,  66.50553406,
        76.49477048,  67.44786519,  51.74004853,  76.02844462,
        59.06544429,  82.10388646,  61.20863649,  98.24901608,
        63.25120061,  70.16907726,  87.20275826,  56.53703525,
        78.41189902,  94.60714131,  50.88775148,  77.76950788,
        78.89824191,  86.72734308,  56.44573934,  55.1931508 ,
        82.82912348,  79.4547701 ,  78.75739276,  80.19672314,
        64.79962918,  78.48380546,  79.3960871 ,  64.28472873,
       100.        ,  82.10749381,  57.13044754,  84.84830413,
        60.37977495,  86.80626906,  92.37893369,  62.68976522,
        89.45064194,  81.1917139 ,  87.3309024 , 100.        ,
        71.31917826,  63.69395753,  61.65728356,  62.76284573,
        73.84347436,  80.11727962,  79.15036199,  87.40774874,
        75.19502838,  96.80301116,  71.0301475 , 100.        ,
        84.38501022,  62.14263665,  58.93661253,  82.23708623,
        71.64805822,  85.71000741,  82.09856437,  73.90756631,
        62.29809423,  52.27729163,  68.30227572,  87.84598191,
        78.21140616,  56.31391832,  77.59771389,  80.7797607 ,
        61.74213846,  77.30587659,  75.87313078,  57.85544553,
        80.36681041,  83.4117679 ,  91.24576865,  90.80703078,
        54.33495948,  60.9326244 ,  82.72552901,  82.70678926,
        82.72571529, 100.        ,  83.56335766,  92.0334846 ,
        89.31002645,  84.77086877,  70.27096133,  86.38453831,
        63.40762178,  71.4477209 ,  67.71954678,  76.22811209,
       100.        ,  46.99102211,  85.29390286,  50.80926193,
        67.92102201,  91.33425895,  75.96420029,  58.83382833,
        64.27044436,  85.19396623,  64.04450052,  78.24687884,
        75.6835776 ,  65.22599479, 100.        ,  84.50878533,
        44.6228612 ,  77.79681472,  65.07320303,  87.78650002,
        63.11218892,  73.27895338,  82.57480918,  87.98632791,
        56.99555389,  69.98248146,  67.87582033,  65.20006151,
       100.        ,  81.07472566,  56.08674068,  88.76792921,
       100.        ,  90.48697891,  52.20945051,  67.73648891,
        94.00366724,  64.38495802,  81.65729142,  86.6195108 ,
        61.09604293,  74.10711966,  26.3809899 ,  59.63418538,
        71.21147773,  56.28325227,  99.48616956,  53.54787933,
        68.3993327 ,  76.96110866,  96.61909934,  53.46206773,
        92.44745628,  75.15349592,  60.27737023,  81.93155211,
        77.98589543,  65.99674684,  76.04703127,  69.22029605,
        76.70276018,  84.93196012,  98.79025224,  56.43276752,
       100.        ,  45.71868301,  72.72322357,  83.8247581 ,
        79.21487802,  65.6595072 ,  71.87816624,  67.60498598,
        66.15952865,  87.74403146,  80.35523229,  64.60635607,
        88.49399813,  79.60949281,  87.19293178,  84.44443263,
        62.56507484,  66.5972844 ,  86.20940408,  84.15555398,
        74.68647609,  76.75991075,  94.16497344,  66.12642917,
        83.20646072,  71.96711021,  71.73478195,  91.48165278,
        87.38124523,  87.20264454,  94.58218211,  75.31505762,
        85.22929457,  70.34599865,  79.86249529,  73.04785418,
        76.45493947,  83.92735538,  62.72668975, 100.        ,
        59.90973928,  56.78717081,  92.3716631 ,  86.87494041,
        84.36179726,  84.42518264,  74.81629841,  61.54118443,
        76.13706837,  64.84257433,  89.626796  ,  72.79413928,
        62.61754205,  70.17921238,  81.19397181,  66.54413171,
        62.66669407,  78.65530817,  78.67449857,  67.39585237,
        67.93442542,  78.48074906,  53.27873488,  53.88804338,
        64.22333668,  71.79829272,  79.66361348,  97.13034325,
        87.86489435,  72.60092205,  74.71475688,  59.96205953,
        74.72230296,  70.67012042,  79.84077841,  62.59153585,
        82.79019771,  97.9910837 ,  73.36859777,  81.02567583,
        85.35215988,  68.98169292,  78.36138723,  75.18888601,
        76.46514148,  63.40485324,  75.36765261,  82.46997437,
        96.76715412,  89.38906239, 100.        ,  63.48978656,
        88.08480955,  77.75013009, 100.        ,  62.87552572,
        62.40417237,  66.00911032,  43.14156414,  67.11367467,
        63.61301008,  77.2559068 ,  80.12633964, 100.        ,
        89.25635757,  66.34644517,  61.52377993,  82.37878757,
        55.19650189, 100.        ,  92.69160181,  67.96236522,
        49.30298206,  95.30808561,  73.28190232,  93.56724468,
        51.08358512,  66.00937466,  75.0786555 ,  75.70470891,
        68.24901793,  84.34274899,  58.98569356,  72.86430772,
        76.80443448,  82.71658251,  85.67422317,  58.13036862,
        51.98828744,  94.16515233,  79.98471018,  63.77270195,
        98.26727963,  76.73511951,  92.68945776,  76.01277722,
       100.        , 100.        ,  71.26553777,  89.57356426,
        84.68063924,  95.52947336,  60.52614809,  85.2907719 ,
        90.8763673 ,  48.6189077 ,  57.25112231,  44.41151733,
        70.95889748,  85.76313384,  97.53535578,  76.11142171,
        99.42923318,  54.29847813,  49.44926341,  74.16678452,
        80.76098173,  74.50957878,  43.9883685 ,  73.66319941,
        55.43295749,  85.04508823,  80.49897369,  60.90180321,
        67.29199624,  59.11179717,  74.05981354,  89.32713481,
        60.2141093 ,  82.56069773,  67.04613572,  63.10690752,
        73.3945446 ,  59.47136516,  66.69526042,  57.03183161,
       100.        ,  75.52895328,  64.50411738,  78.20969866,
        73.31507925,  71.68545601,  84.2125005 ,  86.36261565,
        67.04248279,  66.36272639,  70.87422454,  40.47118253,
        52.27213407,  95.50311401,  99.6745157 ,  71.26445941,
        83.64835445,  79.66875232, 100.        ,  91.79362367,
        73.08123613,  60.66689339,  50.9033052 ,  78.05195454,
        63.65473882,  53.66619436,  65.30140674,  58.77677995,
       100.        ,  88.22459635,  74.88041038,  97.19916208,
        76.16052461,  62.08073698,  97.84686116,  83.08365066,
        59.44130769,  72.14491983,  61.8657262 ,  54.25800404,
        88.89266321, 100.        ,  54.02148639,  83.44453855,
        65.24036146,  67.69311924,  66.11409114,  62.04013845,
        75.72782442,  62.53574825,  79.05685239,  74.24642836,
        71.4157793 ,  61.38654507,  66.34843004,  86.33086839,
        82.51375781,  60.33667133,  76.48998458,  86.27080685,
        49.95892078,  83.15040289,  65.06064362,  83.55898003,
        63.55111265,  47.92676849,  50.58686343,  75.7212742 ,
        78.89583753,  61.43525062,  84.57888688,  50.07719907,
        74.00880302,  56.834757  ,  65.22245838,  75.71098007,
        62.09379952,  69.23166684,  90.09439214,  66.34662196,
        87.53538168,  58.05439718,  82.94706267,  96.62352931,
        37.9253325 ,  63.04657117,  83.65608191,  71.95431921,
        80.5671881 ,  65.9402222 ,  76.29884681,  72.66484147,
        92.51673092,  78.81631265,  80.06403993,  68.82184551,
        67.68590664,  68.51162718,  80.91678214,  68.68523279,
        79.34662285, 100.        ,  88.06687055,  70.10964702,
        93.01820883,  68.8788694 ,  44.42813197,  59.87870534,
        46.93812118,  69.72729774,  75.27627569, 100.        ,
        79.90391061,  71.71349207,  87.44108372,  41.83297036,
        78.53421837,  86.56297791,  52.82120631,  92.15631065,
        80.07744611,  68.77068129,  84.49172799, 100.        ,
        77.72799383,  78.72330879,  68.10958651,  62.25233446,
        87.45503725,  62.15874261,  76.07349356,  67.8351383 ,
        82.18469739,  80.00493158,  90.56309916,  67.34975402,
        70.95187597,  60.31854426,  68.3356011 ,  80.6595074 ,
        86.35482925,  61.16752014,  88.0440888 ,  95.33456788,
        81.20152355, 100.        ,  63.39316201,  56.33017945,
        48.31919627,  97.44066467,  84.81548485,  74.16622994,
        79.19952939,  58.11766429, 100.        ,  76.93831773,
        76.64092192,  85.88649936,  82.21513848,  78.35826036,
        63.14288317,  82.07202536, 100.        ,  95.18130069,
        98.8977994 ,  67.33176485,  60.1559277 ,  73.1131962 ,
        75.83587368,  91.41287278,  49.61303055,  97.94325479,
        72.62988152,  68.59678395,  59.81843437,  50.17714992,
        87.34755876,  76.09976951,  55.6505865 ,  55.57381842,
        69.96322951, 100.        ,  71.10612973,  52.4528557 ,
        71.31385404,  70.90914645,  34.54670036,  74.185577  ,
        71.53598205,  85.44309547, 100.        ,  91.89847544,
        70.96666964,  58.40211137, 100.        ,  75.88827651,
        75.20893938,  74.63812369,  77.97127141,  72.83459382,
        66.3950699 ,  66.79711588,  74.50870095,  66.84862843,
        64.30731326,  76.59645342,  71.17534174,  97.55989483,
        35.23545287,  91.37260278,  93.69127789,  43.89914651,
        69.85968609,  69.42838701,  53.88732458,  63.33274969,
        58.34136232, 100.        ,  89.0351759 ,  94.07332642,
        85.82508096,  58.06422343,  67.13219601,  82.34061842,
        56.66808287,  85.69497645,  71.39511903,  69.37768789,
        85.66439952,  81.66394967,  69.58550751,  92.38994705,
        58.78405009,  84.2390341 ,  83.89651887,  70.35680341,
        79.89199533,  56.23329635,  88.86040529,  72.22646795,
        67.15915469,  90.73513839,  64.43484464,  53.87308055,
        51.6505624 ,  84.09014927,  55.79355971, 100.        ,
        43.77105888, 100.        ,  78.16526201,  73.54930332,
        66.8262137 ,  80.98704172,  74.43547946,  91.54952823,
        76.71341473,  77.25452642,  69.54581682,  74.14581564,
        79.61702653,  49.34747411,  54.77721867,  86.14896141,
        77.56298157,  72.24024995,  75.276509  ,  80.21372558,
        66.9036048 ,  63.32542912,  77.93767883,  60.32440834,
        81.12379134,  49.46124594,  90.43733456,  82.08896224,
        78.84044601,  89.74036476,  99.98211667,  90.21555098,
        47.38688653,  55.8063455 ,  65.62772133,  75.39136575,
        82.76488531,  64.1138428 ,  77.80150147,  63.66925601,
        65.82723296,  53.90008355,  61.15150131,  54.72473092,
        60.36190121,  90.80462695,  60.75901667, 100.        ,
        82.39976851,  77.77254186,  62.1246333 ,  85.50464819,
        66.36543261,  76.83014722, 100.        ,  73.5591015 ,
        92.23909989,  64.45235362,  74.47517264, 100.        ,
        65.59549413, 100.        ,  85.61627903,  66.56299836,
        84.48611609,  89.58831674,  84.32714943,  51.4466292 ,
        64.09294236,  71.28722047,  73.88349856,  84.31008146,
        77.66551501,  54.96983462,  80.70296777,  84.15878618,
        83.39685672,  91.21171088,  87.50883232,  81.88770119,
        73.94751433,  50.085586  ,  81.44427329,  78.11531531,
        79.07368256,  55.84877136,  58.78415189,  90.7972928 ,
        74.40667269,  85.22251046,  75.42477564,  75.44634209,
        89.07425709,  67.25932908,  76.44181165,  68.06587067,
        68.48255659,  70.36241815,  78.33200657,  67.81877068,
        93.83634188,  61.58089047,  72.19692534,  68.40403413,
        96.70466827,  77.94832165,  90.47766809,  52.7165944 ,
        79.00575399,  88.34446193,  76.23425984,  90.98220563,
        67.24067325,  96.1402116 , 100.        ,  69.55742159,
        68.31746218,  96.80076716,  98.69358219,  67.15709959,
        68.69719774,  70.77323087,  54.83324233,  61.2202208 ,
        59.9378885 ,  63.48303652,  74.47972669,  78.51322099,
        98.25750739,  60.02468939,  89.76483598,  71.79016734,
        74.25804436,  85.12229238,  58.15916968,  80.73614619,
        77.49678312,  82.38676896,  79.33752966, 100.        ,
        65.43390024,  67.03504567,  65.6528921 ,  66.66784321,
        65.43919309,  92.83524797,  96.30756372,  66.43880559,
        62.5146664 ,  82.07123335,  66.71665434,  84.49397727,
        78.04384531,  52.26383828,  98.21257802, 100.        ,
        65.80816964,  69.1844766 ,  79.28798086,  80.01685185,
        84.87816409, 100.        ,  72.34579159,  63.02554133,
        54.31021158,  64.0360494 ,  74.50309541, 100.        ,
        67.23583051,  78.35681927,  74.75365656,  92.8258991 ,
       100.        ,  67.03696841,  67.65840836,  90.66241316,
        85.22837234, 100.        ,  83.75892278,  69.61061864,
        83.85982246,  91.63055371,  87.30723272,  82.60911047,
        91.00012034,  92.53943386,  95.73238487,  84.73064831,
        72.4932288 ,  77.2007053 ,  93.0976345 ,  62.74596494,
        80.53009963,  69.09991782,  75.43117234,  94.17677794,
        77.86648602,  75.69654822,  54.60215789,  86.19380349,
        84.68226272, 100.        ,  70.38332648,  78.28725491,
        78.74075526,  98.6617992 ,  73.57056701,  79.18532289,
        84.11844765,  77.79913685,  68.30349578,  77.91134989,
        91.10447625,  59.60227051,  76.99454511,  64.49818778,
        92.92569943,  52.15219643,  66.61617229,  80.65817813,
        98.48286044,  74.01374608,  66.6720071 , 100.        ,
        53.27979149,  42.01791065,  81.60021675,  67.46918663,
        59.68150774,  85.62534671,  78.65701071,  66.53882054,
        55.79543402,  88.08685992,  84.75301767,  73.51236204,
       100.        ,  58.94872851,  52.11712244,  64.62137895,
        74.31620975,  78.65009174,  71.38145913,  80.28083095,
        56.22690864,  96.65646906,  73.76773232,  91.75943747,
        80.1408802 ,  81.85129829,  83.5465092 ,  81.7156284 ,
        84.6408414 ,  94.93728795,  77.94781755,  85.63505636,
        73.65396459,  96.60175823,  64.85411547, 100.        ,
        74.39763074,  53.53837347,  76.92156622,  64.78422514,
        87.60965323,  65.21064031,  68.3072485 ,  46.65688904,
        68.21540521,  38.6418101 ,  51.24145765,  86.40621984,
        86.78700238,  81.38186343,  60.49535785,  74.28432966,
        74.94596191,  57.62452966,  97.55097453,  88.16043436,
        71.68553739,  75.40328758,  78.12574212,  44.37397697,
        71.29233926,  64.77023628,  59.97569985,  70.78349561,
       100.        ,  84.61264292,  66.43231515,  83.58874172])

In [27]:
# 데이터 분석
df_hist = pd.DataFrame({'점수': scores})
df_hist

             점수
0     82.450712
1     72.926035
2     84.715328
3     97.845448
4     71.487699
..          ...
995   70.783496
996  100.000000
997   84.612643
998   66.432315
999   83.588742

[1000 rows x 1 columns]

In [ ]:
# 데이터 시각화
fig = px.histogram(
    df_hist,
    x='점수',
    title='시험 점수 분포',
    nbins=20,  # 구간 수
    marginal='rug'  # 추가 통계 차트: rug, box, violin, histogram
)

'''
nbins=20: 데이터를 쪼갤 막대 격자(Bin)의 개수를 20개로 지정합니다. 0점부터 100점까지의 범위를 20개로 쪼갰으므로, 하나의 막대는 약 5점 단위(0~5, 5~10...)의 범위를 가지며 그 안에 속한 학생 수를 셉니다.
marginal='rug':히스토그램 상단(혹은 하단) 여백에 러그(Rug, 양탄자 술) 플롯을 추가합니다.데이터 포인트 1개당 아주 얇은 세로선 한 줄(|)을 그어주는 방식인데, 막대로 뭉뚱그려진 히스토그램 밑에 실제 데이터가 어디에 촘촘하게 몰려있고 어디가 텅 비었는지 미세하게 짚어주는 서브 차트 역할을 합니다.이 옵션에는 'rug' 외에도 박스플롯을 붙여주는 'box', 바이올린 플롯을 붙여주는 'violin' 등을 넣을 수 있습니다.
'''

fig.update_layout(
    xaxis_title='점수',
    yaxis_title='빈도'
)
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': '점수=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'nbinsx': 20,
              'orientation': 'v',
              'showlegend': False,
              'type': 'histogram',
              'x': {'bdata': ('1+lheNicVEDZ/lMqRDtSQBBDZO/HLV' ... 'WKNSdVQL8zLQ2rm1BAU6rA8a3lVEA='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'boxpoints': 'all',
              'fillcolor': 'rgba(255,255,255,0)',
              'hoveron': 'points',
              'hovertemplate': '점수=%{x}<extra></extra>',
              'jitter': 0,
              'legendgroup': '',
              'line': {'color': 'rgba(255,255,255,0)'},
              'marker': {'color': '#636efa', 'symbol': 'line-ns-open'},
              'name': '',
              'showlegend': False,
              'type': 'box',
              'x': {'bdata': ('1+lheNicVEDZ/lMqRDtSQBBDZO/HLV' ... 'WKNSdVQL8zLQ2rm1BAU6rA8a3lVEA='),
                    'dtype': 'f8'},
              'xaxis': 'x2',
              'yaxis': 'y2'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '시험 점수 분포'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '점수'}},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0], 'matches': 'x', 'showgrid': True, 'showticklabels': False},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 0.8316], 'title': {'text': '빈도'}},
               'yaxis2': {'anchor': 'x2',
                          'domain': [0.8416, 1.0],
                          'matches': 'y2',
                          'showgrid': False,
                          'showline': False,
                          'showticklabels': False,
                          'ticks': ''}}
})

# 2. 그룹별 히스토그램

In [32]:
# 성별 키 분포 비교
height_data = []
np.random.seed(42)

# 남성 키 데이터 (평균 175cm)
male_heights = np.random.normal(175, 6, 500)
for height in male_heights:
    height_data.append({'키': height, '성별': '남성'})

# 여성 키 데이터 (평균 162cm)
female_heights = np.random.normal(162, 5, 500)
for height in female_heights:
    height_data.append({'키': height, '성별': '여성'})

df_heights = pd.DataFrame(height_data)
df_heights

              키  성별
0    177.980285  남성
1    174.170414  남성
2    178.886131  남성
3    184.138179  남성
4    173.595080  남성
..          ...  ..
995  160.594499  여성
996  170.988433  여성
997  165.204214  여성
998  159.144105  여성
999  164.862914  여성

[1000 rows x 2 columns]

In [ ]:
# 데이터 시각화
fig = px.histogram(
    df_heights,
    x='키', 
    color='성별',
    title='성별 키 분포 비교',
    marginal='box',  # 박스플롯 추가
    opacity=0.7, # 불투명도
    barmode='overlay' # 배치 방식: overlay, group, stack, relative
)

fig.update_layout(
    xaxis_title='키 (cm)',
    yaxis_title='빈도'
)

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': '성별=남성<br>키=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '남성',
              'marker': {'color': '#636efa', 'opacity': 0.7, 'pattern': {'shape': ''}},
              'name': '남성',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('kft5fl4/ZkD4MncIdMVlQDba4C9bXG' ... 'l0u2VA6XKSnOE3ZUBk8auggNZkQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'hovertemplate': '성별=남성<br>키=%{x}<extra></extra>',
              'legendgroup': '남성',
              'marker': {'color': '#636efa'},
              'name': '남성',
              'notched': True,
              'showlegend': False,
              'type': 'box',
              'x': {'bdata': ('kft5fl4/ZkD4MncIdMVlQDba4C9bXG' ... 'l0u2VA6XKSnOE3ZUBk8auggNZkQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x2',
              'yaxis': 'y2'},
             {'bingroup': 'x',
              'hovertemplate': '성별=여성<br>키=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '여성',
              'marker': {'color': '#EF553B', 'opacity': 0.7, 'pattern': {'shape': ''}},
              'name': '여성',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('EBZ7OzDUZEAvyaG0gXFlQB7AE6w6YG' ... 'yIpmRASzMygpzkY0BjHKD9nJtkQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'hovertemplate': '성별=여성<br>키=%{x}<extra></extra>',
              'legendgroup': '여성',
              'marker': {'color': '#EF553B'},
              'name': '여성',
              'notched': True,
              'showlegend': False,
              'type': 'box',
              'x': {'bdata': ('EBZ7OzDUZEAvyaG0gXFlQB7AE6w6YG' ... 'yIpmRASzMygpzkY0BjHKD9nJtkQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x2',
              'yaxis': 'y2'}],
    'layout': {'barmode': 'overlay',
               'legend': {'title': {'text': '성별'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': '성별 키 분포 비교'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': '키 (cm)'}},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0], 'matches': 'x', 'showgrid': True, 'showticklabels': False},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 0.7326], 'title': {'text': '빈도'}},
               'yaxis2': {'anchor': 'x2',
                          'domain': [0.7426, 1.0],
                          'matches': 'y2',
                          'showgrid': False,
                          'showline': False,
                          'showticklabels': False,
                          'ticks': ''}}
})

## 캔들스틱 차트(주가 데이터용)

In [ ]:
# 기본 캔들스틱 차트
# 주가 데이터 셍성
datetime.now()

datetime.datetime(2026, 7, 20, 11, 37, 45, 397379)

In [36]:
dates = [datetime.now() - timedelta(days=x) for x in range(30, 0, -1)]
dates

[datetime.datetime(2026, 6, 20, 11, 43, 44, 349116),
 datetime.datetime(2026, 6, 21, 11, 43, 44, 349116),
 datetime.datetime(2026, 6, 22, 11, 43, 44, 349116),
 datetime.datetime(2026, 6, 23, 11, 43, 44, 349116),
 datetime.datetime(2026, 6, 24, 11, 43, 44, 349116),
 datetime.datetime(2026, 6, 25, 11, 43, 44, 349116),
 datetime.datetime(2026, 6, 26, 11, 43, 44, 349116),
 datetime.datetime(2026, 6, 27, 11, 43, 44, 349116),
 datetime.datetime(2026, 6, 28, 11, 43, 44, 349116),
 datetime.datetime(2026, 6, 29, 11, 43, 44, 349116),
 datetime.datetime(2026, 6, 30, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 1, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 2, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 3, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 4, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 5, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 6, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 7, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 8, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 9, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 10, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 11, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 12, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 13, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 14, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 15, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 16, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 17, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 18, 11, 43, 44, 349116),
 datetime.datetime(2026, 7, 19, 11, 43, 44, 349116)]

In [40]:
np.random.seed(42)

ohlc_data = []
price = 100

for date in dates:
    open_price = price
    high_price = open_price + np.random.uniform(0, 5)
    low_price = open_price - np.random.uniform(0, 5)
    close_price = open_price + np.random.uniform(-3, 3)

    ohlc_data.append({
        '날짜': date,
        '시가': open_price,
        '고가': high_price,
        '저가': low_price,
        '종가': close_price
    })

    price = close_price

df_ohlc = pd.DataFrame(ohlc_data)
df_ohlc

                           날짜          시가          고가          저가          종가
0  2026-06-20 11:43:44.349116  100.000000  101.872701   95.246428  101.391964
1  2026-06-21 11:43:44.349116  101.391964  104.385256  100.611870   99.327931
2  2026-06-22 11:43:44.349116   99.327931   99.618349   94.997050   99.934621
3  2026-06-23 11:43:44.349116   99.934621  103.474984   99.831698  102.754080
4  2026-06-24 11:43:44.349116  102.754080  106.916293  101.692384  100.845030
5  2026-06-25 11:43:44.349116  100.845030  101.762052   99.323819  100.993568
6  2026-06-26 11:43:44.349116  100.993568  103.153293   99.537423  101.664686
7  2026-06-27 11:43:44.349116  101.664686  102.362155  100.203962  100.862857
8  2026-06-28 11:43:44.349116  100.862857  103.143207   96.936977   99.060899
9  2026-06-29 11:43:44.349116   99.060899  101.632072   96.098827   96.339602
10 2026-06-30 11:43:44.349116   96.339602   99.377326   95.486981   93.729912
11 2026-07-01 11:43:44.349116   93.729912   98.474339   88.901751   95.580296
12 2026-07-02 11:43:44.349116   95.580296   97.103364   95.091935   96.685694
13 2026-07-03 11:43:44.349116   96.685694   98.886456   96.075503   96.656755
14 2026-07-04 11:43:44.349116   96.656755   96.828698   92.110153   95.209435
15 2026-07-05 11:43:44.349116   95.209435   98.522047   93.650880   95.329843
16 2026-07-06 11:43:44.349116   95.329843   98.063395   94.405571   98.147351
17 2026-07-07 11:43:44.349116   98.147351  102.023015   93.449856  100.516315
18 2026-07-08 11:43:44.349116  100.516315  103.505815   95.906944   98.047270
19 2026-07-09 11:43:44.349116   98.047270   99.027184   97.821134   96.999252
20 2026-07-10 11:43:44.349116   96.999252   98.942639   95.642507   98.971677
21 2026-07-11 11:43:44.349116   98.971677  100.755444   97.567005   99.227854
22 2026-07-12 11:43:44.349116   99.227854   99.932475   95.216869   96.675158
23 2026-07-13 11:43:44.349116   96.675158  101.609592   92.813934   94.867452
24 2026-07-14 11:43:44.349116   94.867452   94.895062   90.790144   96.108596
25 2026-07-15 11:43:44.349116   96.108596   99.753632   92.252244   93.552864
26 2026-07-16 11:43:44.349116   93.552864   95.345192   92.973518   95.731484
27 2026-07-17 11:43:44.349116   95.731484   98.847975   94.076994   93.112834
28 2026-07-18 11:43:44.349116   93.112834   94.667746   91.486918   94.490471
29 2026-07-19 11:43:44.349116   94.490471   97.678259   90.054408   94.323761

In [43]:
# 캔들스틱 차트 생성
import plotly.graph_objects as go

fig = go.Figure(data=go.Candlestick(
    x=df_ohlc['날짜'],
    open=df_ohlc['시가'],
    high=df_ohlc['고가'],
    low=df_ohlc['저가'],
    close=df_ohlc['종가'],
    name='주가'
))

fig.update_layout(
    title='일별 주가 캔들스틱 차트',
    xaxis_title='날짜',
    yaxis_title='가격',
    xaxis_rangeslider_visible=False # 하단 범위 슬라이더 제거
)

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'close': {'bdata': ('2Gy17hVZWUBWOVrR/NRYQOIU8dPQ+1' ... 'sRrThHV0AGzb3hY59XQG4ucH+4lFdA'),
                        'dtype': 'f8'},
              'high': {'bdata': ('mtyXU9p3WUCXTBUJqBhaQAuY/AaT51' ... 'jxN0W2WEAXLAxZvKpXQC3KAJdoa1hA'),
                       'dtype': 'f8'},
              'low': {'bdata': ('oanoe8XPV0CEl6viKCdZQCng/KrPv1' ... '1DeO2EV0AdyIaoKd9WQORZ92l7g1ZA'),
                      'dtype': 'f8'},
              'name': '주가',
              'open': {'bdata': ('AAAAAAAAWUDYbLXuFVlZQFY5WtH81F' ... '7PotDuV0AoaxGtOEdXQAbNveFjn1dA'),
                       'dtype': 'f8'},
              'type': 'candlestick',
              'x': array(['2026-06-20T11:43:44.349116', '2026-06-21T11:43:44.349116',
                          '2026-06-22T11:43:44.349116', '2026-06-23T11:43:44.349116',
                          '2026-06-24T11:43:44.349116', '2026-06-25T11:43:44.349116',
                          '2026-06-26T11:43:44.349116', '2026-06-27T11:43:44.349116',
                          '2026-06-28T11:43:44.349116', '2026-06-29T11:43:44.349116',
                          '2026-06-30T11:43:44.349116', '2026-07-01T11:43:44.349116',
                          '2026-07-02T11:43:44.349116', '2026-07-03T11:43:44.349116',
                          '2026-07-04T11:43:44.349116', '2026-07-05T11:43:44.349116',
                          '2026-07-06T11:43:44.349116', '2026-07-07T11:43:44.349116',
                          '2026-07-08T11:43:44.349116', '2026-07-09T11:43:44.349116',
                          '2026-07-10T11:43:44.349116', '2026-07-11T11:43:44.349116',
                          '2026-07-12T11:43:44.349116', '2026-07-13T11:43:44.349116',
                          '2026-07-14T11:43:44.349116', '2026-07-15T11:43:44.349116',
                          '2026-07-16T11:43:44.349116', '2026-07-17T11:43:44.349116',
                          '2026-07-18T11:43:44.349116', '2026-07-19T11:43:44.349116'],
                         dtype='datetime64[us]')}],
    'layout': {'template': '...',
               'title': {'text': '일별 주가 캔들스틱 차트'},
               'xaxis': {'rangeslider': {'visible': False}, 'title': {'text': '날짜'}},
               'yaxis': {'title': {'text': '가격'}}}
})

In [44]:
## 2. 거래량과 함께 표시
df_ohlc['거래량'] = np.random.randint(1000, 10000, len(df_ohlc))

In [ ]:
# 서브플롯 생성
fig = make_subplots(
    rows=2, 
    cols=1,
    shared_xaxes=True,
    vertical_spacing=0.03,
    subplot_titles=('주가', '거래량'),
    row_width=[0.2, 0.7]
)

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [],
    'layout': {'annotations': [{'font': {'size': 16},
                                'showarrow': False,
                                'text': '주가',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': '거래량',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.21555555555555558,
                                'yanchor': 'bottom',
                                'yref': 'paper'}],
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'matches': 'x2', 'showticklabels': False},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0]},
               'yaxis': {'anchor': 'x', 'domain': [0.24555555555555558, 1.0]},
               'yaxis2': {'anchor': 'x2', 'domain': [0.0, 0.21555555555555558]}}
})

In [47]:
# 캔들스틱 차트
fig.add_trace(go.Candlestick(
        x=df_ohlc['날짜'],
        open=df_ohlc['시가'],
        high=df_ohlc['고가'],
        low=df_ohlc['저가'],
        close=df_ohlc['종가'],
        name='주가'
    ), row=1, col=1)

fig.update_layout(
    title='주가와 거래량',
    xaxis_rangeslider_visible=False
)

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'close': {'bdata': ('2Gy17hVZWUBWOVrR/NRYQOIU8dPQ+1' ... 'sRrThHV0AGzb3hY59XQG4ucH+4lFdA'),
                        'dtype': 'f8'},
              'high': {'bdata': ('mtyXU9p3WUCXTBUJqBhaQAuY/AaT51' ... 'jxN0W2WEAXLAxZvKpXQC3KAJdoa1hA'),
                       'dtype': 'f8'},
              'low': {'bdata': ('oanoe8XPV0CEl6viKCdZQCng/KrPv1' ... '1DeO2EV0AdyIaoKd9WQORZ92l7g1ZA'),
                      'dtype': 'f8'},
              'name': '주가',
              'open': {'bdata': ('AAAAAAAAWUDYbLXuFVlZQFY5WtH81F' ... '7PotDuV0AoaxGtOEdXQAbNveFjn1dA'),
                       'dtype': 'f8'},
              'type': 'candlestick',
              'x': array(['2026-06-20T11:43:44.349116', '2026-06-21T11:43:44.349116',
                          '2026-06-22T11:43:44.349116', '2026-06-23T11:43:44.349116',
                          '2026-06-24T11:43:44.349116', '2026-06-25T11:43:44.349116',
                          '2026-06-26T11:43:44.349116', '2026-06-27T11:43:44.349116',
                          '2026-06-28T11:43:44.349116', '2026-06-29T11:43:44.349116',
                          '2026-06-30T11:43:44.349116', '2026-07-01T11:43:44.349116',
                          '2026-07-02T11:43:44.349116', '2026-07-03T11:43:44.349116',
                          '2026-07-04T11:43:44.349116', '2026-07-05T11:43:44.349116',
                          '2026-07-06T11:43:44.349116', '2026-07-07T11:43:44.349116',
                          '2026-07-08T11:43:44.349116', '2026-07-09T11:43:44.349116',
                          '2026-07-10T11:43:44.349116', '2026-07-11T11:43:44.349116',
                          '2026-07-12T11:43:44.349116', '2026-07-13T11:43:44.349116',
                          '2026-07-14T11:43:44.349116', '2026-07-15T11:43:44.349116',
                          '2026-07-16T11:43:44.349116', '2026-07-17T11:43:44.349116',
                          '2026-07-18T11:43:44.349116', '2026-07-19T11:43:44.349116'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'yaxis': 'y'},
             {'close': {'bdata': ('2Gy17hVZWUBWOVrR/NRYQOIU8dPQ+1' ... 'sRrThHV0AGzb3hY59XQG4ucH+4lFdA'),
                        'dtype': 'f8'},
              'high': {'bdata': ('mtyXU9p3WUCXTBUJqBhaQAuY/AaT51' ... 'jxN0W2WEAXLAxZvKpXQC3KAJdoa1hA'),
                       'dtype': 'f8'},
              'low': {'bdata': ('oanoe8XPV0CEl6viKCdZQCng/KrPv1' ... '1DeO2EV0AdyIaoKd9WQORZ92l7g1ZA'),
                      'dtype': 'f8'},
              'name': '주가',
              'open': {'bdata': ('AAAAAAAAWUDYbLXuFVlZQFY5WtH81F' ... '7PotDuV0AoaxGtOEdXQAbNveFjn1dA'),
                       'dtype': 'f8'},
              'type': 'candlestick',
              'x': array(['2026-06-20T11:43:44.349116', '2026-06-21T11:43:44.349116',
                          '2026-06-22T11:43:44.349116', '2026-06-23T11:43:44.349116',
                          '2026-06-24T11:43:44.349116', '2026-06-25T11:43:44.349116',
                          '2026-06-26T11:43:44.349116', '2026-06-27T11:43:44.349116',
                          '2026-06-28T11:43:44.349116', '2026-06-29T11:43:44.349116',
                          '2026-06-30T11:43:44.349116', '2026-07-01T11:43:44.349116',
                          '2026-07-02T11:43:44.349116', '2026-07-03T11:43:44.349116',
                          '2026-07-04T11:43:44.349116', '2026-07-05T11:43:44.349116',
                          '2026-07-06T11:43:44.349116', '2026-07-07T11:43:44.349116',
                          '2026-07-08T11:43:44.349116', '2026-07-09T11:43:44.349116',
                          '2026-07-10T11:43:44.349116', '2026-07-11T11:43:44.349116',
                          '2026-07-12T11:43:44.349116', '2026-07-13T11:43:44.349116',
                          '2026-07-14T11:43:44.349116', '2026-07-15T11:43:44.349116',
                          '2026-07-16T11:43:44.349116', '2026-07-17T11:43:44.349116',
                          '2026-07-18T11:43:44.349116', '2026-07-19T11:43:44.349116'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'annotations': [{'font': {'size': 16},
                                'showarrow': False,
                                'text': '주가',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': '거래량',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.21555555555555558,
                                'yanchor': 'bottom',
                                'yref': 'paper'}],
               'template': '...',
               'title': {'text': '주가와 거래량'},
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'matches': 'x2',
                         'rangeslider': {'visible': False},
                         'showticklabels': False},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0]},
               'yaxis': {'anchor': 'x', 'domain': [0.24555555555555558, 1.0]},
               'yaxis2': {'anchor': 'x2', 'domain': [0.0, 0.21555555555555558]}}
})

In [48]:
# 거래량 박대 차트
fig.add_trace(
    go.Bar(
        x=df_ohlc['날짜'],
        y=df_ohlc['거래량'],
        name='거래량',
        marker_color='rgba(158,202,225,0.8)'
    ),
    row=2, col=1
)

fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'close': {'bdata': ('2Gy17hVZWUBWOVrR/NRYQOIU8dPQ+1' ... 'sRrThHV0AGzb3hY59XQG4ucH+4lFdA'),
                        'dtype': 'f8'},
              'high': {'bdata': ('mtyXU9p3WUCXTBUJqBhaQAuY/AaT51' ... 'jxN0W2WEAXLAxZvKpXQC3KAJdoa1hA'),
                       'dtype': 'f8'},
              'low': {'bdata': ('oanoe8XPV0CEl6viKCdZQCng/KrPv1' ... '1DeO2EV0AdyIaoKd9WQORZ92l7g1ZA'),
                      'dtype': 'f8'},
              'name': '주가',
              'open': {'bdata': ('AAAAAAAAWUDYbLXuFVlZQFY5WtH81F' ... '7PotDuV0AoaxGtOEdXQAbNveFjn1dA'),
                       'dtype': 'f8'},
              'type': 'candlestick',
              'x': array(['2026-06-20T11:43:44.349116', '2026-06-21T11:43:44.349116',
                          '2026-06-22T11:43:44.349116', '2026-06-23T11:43:44.349116',
                          '2026-06-24T11:43:44.349116', '2026-06-25T11:43:44.349116',
                          '2026-06-26T11:43:44.349116', '2026-06-27T11:43:44.349116',
                          '2026-06-28T11:43:44.349116', '2026-06-29T11:43:44.349116',
                          '2026-06-30T11:43:44.349116', '2026-07-01T11:43:44.349116',
                          '2026-07-02T11:43:44.349116', '2026-07-03T11:43:44.349116',
                          '2026-07-04T11:43:44.349116', '2026-07-05T11:43:44.349116',
                          '2026-07-06T11:43:44.349116', '2026-07-07T11:43:44.349116',
                          '2026-07-08T11:43:44.349116', '2026-07-09T11:43:44.349116',
                          '2026-07-10T11:43:44.349116', '2026-07-11T11:43:44.349116',
                          '2026-07-12T11:43:44.349116', '2026-07-13T11:43:44.349116',
                          '2026-07-14T11:43:44.349116', '2026-07-15T11:43:44.349116',
                          '2026-07-16T11:43:44.349116', '2026-07-17T11:43:44.349116',
                          '2026-07-18T11:43:44.349116', '2026-07-19T11:43:44.349116'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'yaxis': 'y'},
             {'close': {'bdata': ('2Gy17hVZWUBWOVrR/NRYQOIU8dPQ+1' ... 'sRrThHV0AGzb3hY59XQG4ucH+4lFdA'),
                        'dtype': 'f8'},
              'high': {'bdata': ('mtyXU9p3WUCXTBUJqBhaQAuY/AaT51' ... 'jxN0W2WEAXLAxZvKpXQC3KAJdoa1hA'),
                       'dtype': 'f8'},
              'low': {'bdata': ('oanoe8XPV0CEl6viKCdZQCng/KrPv1' ... '1DeO2EV0AdyIaoKd9WQORZ92l7g1ZA'),
                      'dtype': 'f8'},
              'name': '주가',
              'open': {'bdata': ('AAAAAAAAWUDYbLXuFVlZQFY5WtH81F' ... '7PotDuV0AoaxGtOEdXQAbNveFjn1dA'),
                       'dtype': 'f8'},
              'type': 'candlestick',
              'x': array(['2026-06-20T11:43:44.349116', '2026-06-21T11:43:44.349116',
                          '2026-06-22T11:43:44.349116', '2026-06-23T11:43:44.349116',
                          '2026-06-24T11:43:44.349116', '2026-06-25T11:43:44.349116',
                          '2026-06-26T11:43:44.349116', '2026-06-27T11:43:44.349116',
                          '2026-06-28T11:43:44.349116', '2026-06-29T11:43:44.349116',
                          '2026-06-30T11:43:44.349116', '2026-07-01T11:43:44.349116',
                          '2026-07-02T11:43:44.349116', '2026-07-03T11:43:44.349116',
                          '2026-07-04T11:43:44.349116', '2026-07-05T11:43:44.349116',
                          '2026-07-06T11:43:44.349116', '2026-07-07T11:43:44.349116',
                          '2026-07-08T11:43:44.349116', '2026-07-09T11:43:44.349116',
                          '2026-07-10T11:43:44.349116', '2026-07-11T11:43:44.349116',
                          '2026-07-12T11:43:44.349116', '2026-07-13T11:43:44.349116',
                          '2026-07-14T11:43:44.349116', '2026-07-15T11:43:44.349116',
                          '2026-07-16T11:43:44.349116', '2026-07-17T11:43:44.349116',
                          '2026-07-18T11:43:44.349116', '2026-07-19T11:43:44.349116'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'yaxis': 'y'},
             {'marker': {'color': 'rgba(158,202,225,0.8)'},
              'name': '거래량',
              'type': 'bar',
              'x': array(['2026-06-20T11:43:44.349116', '2026-06-21T11:43:44.349116',
                          '2026-06-22T11:43:44.349116', '2026-06-23T11:43:44.349116',
                          '2026-06-24T11:43:44.349116', '2026-06-25T11:43:44.349116',
                          '2026-06-26T11:43:44.349116', '2026-06-27T11:43:44.349116',
                          '2026-06-28T11:43:44.349116', '2026-06-29T11:43:44.349116',
                          '2026-06-30T11:43:44.349116', '2026-07-01T11:43:44.349116',
                          '2026-07-02T11:43:44.349116', '2026-07-03T11:43:44.349116',
                          '2026-07-04T11:43:44.349116', '2026-07-05T11:43:44.349116',
                          '2026-07-06T11:43:44.349116', '2026-07-07T11:43:44.349116',
                          '2026-07-08T11:43:44.349116', '2026-07-09T11:43:44.349116',
                          '2026-07-10T11:43:44.349116', '2026-07-11T11:43:44.349116',
                          '2026-07-12T11:43:44.349116', '2026-07-13T11:43:44.349116',
                          '2026-07-14T11:43:44.349116', '2026-07-15T11:43:44.349116',
                          '2026-07-16T11:43:44.349116', '2026-07-17T11:43:44.349116',
                          '2026-07-18T11:43:44.349116', '2026-07-19T11:43:44.349116'],
                         dtype='datetime64[us]'),
              'xaxis': 'x2',
              'y': {'bdata': ('liMAAOgSAADsBwAAwSAAAN4FAADmHg' ... '4AAHYKAACSEAAABBYAAAsIAAD0HQAA'),
                    'dtype': 'i4'},
              'yaxis': 'y2'}],
    'layout': {'annotations': [{'font': {'size': 16},
                                'showarrow': False,
                                'text': '주가',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': '거래량',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.21555555555555558,
                                'yanchor': 'bottom',
                                'yref': 'paper'}],
               'template': '...',
               'title': {'text': '주가와 거래량'},
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'matches': 'x2',
                         'rangeslider': {'visible': False},
                         'showticklabels': False},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0]},
               'yaxis': {'anchor': 'x', 'domain': [0.24555555555555558, 1.0]},
               'yaxis2': {'anchor': 'x2', 'domain': [0.0, 0.21555555555555558]}}
})