In [1]:
# 데이터 통합

In [2]:
import pandas as pd

In [3]:
# 두 개의 통합혈 데이터프레임
df1 = pd.DataFrame({
    'ID': ['1', '2', '3'],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': ['4', '5', '6'],
    'Name': ['David', 'Eva', 'Frank']
})

In [4]:
df1

  ID     Name
0  1    Alice
1  2      Bob
2  3  Charlie

In [5]:
df2

  ID   Name
0  4  David
1  5    Eva
2  6  Frank

In [6]:
# 데이터프레임 df1과 df2를 행(Row) 기준으로 연결(위아래로 붙이기)
result_concat = pd.concat([df1, df2], axis=0, ignore_index=True)
print(result_concat)

  ID     Name
0  1    Alice
1  2      Bob
2  3  Charlie
3  4    David
4  5      Eva
5  6    Frank

In [7]:
# ignore_index=True -> 기존 인덱스 무시
# axis 기본값은 0(위에서 아래로 붙이기)
pd.concat([df1, df2], axis=0, ignore_index=True)

  ID     Name
0  1    Alice
1  2      Bob
2  3  Charlie
3  4    David
4  5      Eva
5  6    Frank

In [8]:
# 데이터 열 기준 결합
df3 = pd.DataFrame({
    'age': [25, 30, 35]
})
df3

   age
0   25
1   30
2   35

In [10]:
# 데이터프레임 df1과 df3를 열(Column) 기준으로 연결(좌우로 붙이기)
pd.concat([df1, df3], axis=1)

  ID     Name  age
0  1    Alice   25
1  2      Bob   30
2  3  Charlie   35

In [11]:
# 데이터 병합(Merge): inner(기본값), left, right, outer
df4 = pd.DataFrame({
    'ID': ['1', '2', '4', '5'],
    'Score': [85, 90, 95, 80]
})
df4

  ID  Score
0  1     85
1  2     90
2  4     95
3  5     80

In [13]:
# 두 데이터프레임을 'ID'를 기준으로 병합 (기본: inner join)
pd.merge(df1, df4, on='ID', how='inner')

  ID   Name  Score
0  1  Alice     85
1  2    Bob     90

In [14]:
# 샘플 데이터프레임을 왼쪽 데이터셋(df1)의 'ID'를 키로 설정하여 병합
pd.merge(df1, df4, on='ID', how='left')

  ID     Name  Score
0  1    Alice   85.0
1  2      Bob   90.0
2  3  Charlie    NaN

In [15]:
# 샘플 데이터프레임을 오른쪽 데이터셋(df4)의 'ID'를 키로 설정하여 병합
pd.merge(df1, df4, on='ID', how='right')

  ID   Name  Score
0  1  Alice     85
1  2    Bob     90
2  4    NaN     95
3  5    NaN     80

In [16]:
# 샘플 데이터프레임의 'ID'를 키로 설정하여 모든 데이터가 포함되도록 병합
pd.merge(df1, df4, on='ID', how='outer')

  ID     Name  Score
0  1    Alice   85.0
1  2      Bob   90.0
2  3  Charlie    NaN
3  4      NaN   95.0
4  5      NaN   80.0